version: '3'
services:
  server:
    build: ./server
    expose:
      - 8000
    ports:
      - "8000:8000"
  client:
    build: ./client
    depends_on:
      - server
    expose:
      - 80
    ports:
      - "80:80"
    stdin_open: true
